### PR TITLE
fix(dialog): calculate contrast ripple color for button

### LINKED ISSUE #5: Missing ripple effect on button click
We need some ripple or other effect to improve user experience

### PR DESCRIPTION
**Pull request by arkadiuszpalka**
Resolves #5

### CODE REVIEW

File: sdk/src/main/java/com/hellocustomer/sdk/utility/ColorExt.kt [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+@ColorInt
+internal fun getContrastColor(
+    backgroundColor: Int,
+    @ColorInt darkColor: Int = Color.BLACK,
+    @ColorInt lightColor: Int = Color.WHITE
+): Int {
+    val darkness = 1 - (0.299 * Color.red(backgroundColor) + 0.587 * Color.green(
+        backgroundColor
+    ) + 0.114 * Color.blue(backgroundColor)) / 255
```
Comment (PiotrBandurski) [inline sdk/src/main/java/com/hellocustomer/sdk/utility/ColorExt.kt:20]: consts please :D
